import java.util.Scanner;
public class Patient extends Personne{
    private String adresse;
    private String CIN;
    private String dateDeNaissance;
    private Dossier dossier;


    public Patient(String nom, String prenom, int numTelephone, String adresse, String CIN, String dateDeNaissance, Dossier dossier) {
        super(nom, prenom, numTelephone);
        this.adresse = adresse;
        this.CIN = CIN;
        this.dateDeNaissance = dateDeNaissance;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public String getDateDeNaissance() {
        return dateDeNaissance;
    }

    public void setDateDeNaissance(String dateDeNaissance) {
        this.dateDeNaissance = dateDeNaissance;
    }

    public String getCIN() {
        return CIN;
    }

    public void setCIN(String CIN) {
        this.CIN = CIN;
    }
    public static Prescription givePrescription() {
        Scanner scanner = new Scanner(System.in);
        //need to check if the type exist in the categorie json file
        //else raise an excep
        System.out.println("Enter the traitement name:");
        String type = scanner.nextLine();


        System.out.println("Enter the doctor's first name:");
        String doctorFirstName = scanner.nextLine();

        System.out.println("Enter the doctor's last name:");
        String doctorLastName = scanner.nextLine();

        System.out.println("Enter the doctor's phone number:");
        int doctorPhone = scanner.nextInt();
        scanner.nextLine();
        //this ID will be autogenerated or can be even deleted from the medecin
        System.out.println("Enter the doctor's ID:");
        String doctorID = scanner.nextLine();

        System.out.println("Enter the doctor's specialty:");
        String doctorSpecialty = scanner.nextLine();

        System.out.println("Enter the doctor's contact:");
        String doctorContact = scanner.nextLine();

        Medecin medecin = new Medecin(doctorFirstName, doctorLastName, doctorPhone, doctorID, doctorSpecialty, doctorContact);
        return new Prescription(type, medecin);
    }
}
