package entity;

import java.util.Scanner;

//note every instance shall be saves into a json file
//so we can every patient have his own treatement(based on the categorie)
public class RendezVous {
    //when creating a rdv make sure that this  patient has no rdv not done
    //Date date;
    private int idRv;
    private Patient patient;
    private Prescription prescription;//base on this schedule the rendez-vous
    private String state="Waiting";
    RendezVous(int idRv, Patient patient) {
        this.idRv = idRv;
        this.patient = patient;
        //static because every patient will give his prescrption
       generatePrescription();
        //this.date=date;
    }
    private void generatePrescription() {
        Scanner scanner = new Scanner(System.in);
        //need to check if the type exist in the categorie json file
        //else raise an excep
        System.out.println("Enter the traitement name:");
        String type = scanner.nextLine();


        System.out.println("Enter the doctor's first name:");
        String doctorFirstName = scanner.nextLine();

        System.out.println("Enter the doctor's last name:");
        String doctorLastName = scanner.nextLine();

        System.out.println("Enter the doctor's phone number:");
        int doctorPhone = scanner.nextInt();
        scanner.nextLine();
        //this ID will be autogenerated or can be even deleted from the medecin
        System.out.println("Enter the doctor's ID:");
        String doctorID = scanner.nextLine();

        System.out.println("Enter the doctor's specialty:");
        String doctorSpecialty = scanner.nextLine();

        System.out.println("Enter the doctor's contact:");
        String doctorContact = scanner.nextLine();

        Medecin medecin = new Medecin(doctorFirstName, doctorLastName, doctorPhone, doctorID, doctorSpecialty, doctorContact);
        this.prescription=new Prescription(type, medecin);
    }
    private void scheduleRDV(){
        //schedule the rdv
    }
    public Prescription getPrescription() {
        return prescription;
    }

    public void setPrescription(Prescription prescription) {
        this.prescription = prescription;
    }

    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public int getIdRv() {
        return idRv;
    }

    public void setIdRv(int idRv) {
        this.idRv = idRv;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }


}
