package ihm;

import entity.*;

import java.util.Scanner;

public class RendezVousIhm {
    public static int RdvManagementMenu() {
        Scanner scanner = new Scanner(System.in);
        System.out.println("\n--- Rendez-Vous MANAGEMENT ---");
        System.out.println("1. Add Rendez-Vous");
        System.out.println("2. Remove Rendez-Vous ");
        System.out.println("3. View Rendez-Vous");
        System.out.println("4. List All Rendez-Vous");
        System.out.println("5. Return to Main Menu");
        System.out.print("Enter your choice: ");

        int choice = scanner.nextInt();
        scanner.nextLine(); // Consume newline
        return choice;
    }

    public static RendezVous addRendezVous() {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Id RendezVous : ");
        int Idr= scanner.nextInt();
        scanner.nextLine();
        Patient patient=PatientIhm.addPatient();
        System.out.println("Type The Prescription : ");
        Prescription prescription=generatePrescription();
        return new RendezVous(Idr,patient);
    }
    private static Prescription generatePrescription() {
        Scanner scanner = new Scanner(System.in);
        //need to check if the type exist in the categorie json file
        //else raise an excep
        System.out.println("Enter the traitement name:");
        String type = scanner.nextLine();


        System.out.println("Enter the doctor's first name:");
        String doctorFirstName = scanner.nextLine();

        System.out.println("Enter the doctor's last name:");
        String doctorLastName = scanner.nextLine();

        System.out.println("Enter the doctor's phone number:");
        int doctorPhone = scanner.nextInt();
        scanner.nextLine();
        //this ID will be autogenerated or can be even deleted from the medecin
        System.out.println("Enter the doctor's ID:");
        int doctorID = scanner.nextInt();

        System.out.println("Enter the doctor's specialty:");
        String doctorSpecialty = scanner.nextLine();
        scanner.nextLine();
        System.out.println("Enter the doctor's contact:");
        String doctorContact = scanner.nextLine();

        Medecin medecin = new Medecin(doctorFirstName, doctorLastName, doctorPhone, doctorID, doctorSpecialty, doctorContact);
        return new Prescription(type, medecin);
    }
    public static int removeRendezVous() {
        System.out.print("Enter Medecin ID to remove: ");
        Scanner scanner = new Scanner(System.in);
        int idM = scanner.nextInt();

        return idM;
    }

    public static int viewRendezVous() {
        System.out.print("Enter Medecin ID to view: ");
        Scanner scanner = new Scanner(System.in);
        int idM = scanner.nextInt();

        return idM;
    }
}